name: Lint R Code

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup R
      uses: r-lib/actions/setup-r@master
      with:
        r-version: 4.0.4
    - name: Install libcurl for lintr
      run: sudo apt install libcurl4-openssl-dev
    - name: Install lintr
      run: |
        install.packages('lintr')
      shell: RScript {0}
    - name: Run lintr
      run: Rscript -e "lintr::lint_dir(path = '.', relative_path = TRUE)"
