name: Lint R Code

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@master
    - name: Run lintr
      run: |
        Rscript -e "lintr::lint_dir(path = '.', relative_path = TRUE)"
